KERNEL_DIR=/home/pi/build

ARCH=arm
CROSS_COMPILE=arm-linux-gnueabihf-
export  ARCH  CROSS_COMPILE

obj-m := paj7620_1.o 

all:app
	$(MAKE) -C $(KERNEL_DIR) M=$(CURDIR) modules

app:
	arm-linux-gnueabihf-gcc app.c -lm -o App

.PHONE:clean copy 

clean:
	$(MAKE) -C $(KERNEL_DIR) M=$(CURDIR) clean
	sudo rm  /home/guang01/workdir/*.ko	App

copy:
	sudo  cp  *.ko App  /home/guang01/workdir